import type { HanziKnowledgeCard } from '../schema';
import { SAMPLE_HANZI_SOURCE } from '../sources';

type HanziTuple = [
  char: string,
  pinyin: string,
  wuxing: HanziKnowledgeCard['wuxing'],
  meaning: string,
  genderFit: HanziKnowledgeCard['genderFit'],
  styleTags: string[],
  riskTags?: string[],
];

const ADDITIONAL_HANZI_SAMPLE: HanziKnowledgeCard[] = ([
  ['洛', 'luo', '水', '洛水、清雅', ['female', 'neutral'], ['清雅', '诗意'], []],
  ['溪', 'xi', '水', '溪流、澄澈', ['female', 'neutral'], ['清雅', '自然'], []],
  ['澜', 'lan', '水', '波澜、开阔', ['male', 'female', 'neutral'], ['大气', '明朗'], []],
  ['汐', 'xi', '水', '潮汐、灵动', ['female', 'neutral'], ['清雅', '诗意'], ['overused']],
  ['沅', 'yuan', '水', '沅水、清润', ['female', 'male', 'neutral'], ['诗意', '自然'], []],
  ['湘', 'xiang', '水', '湘水、文雅', ['female', 'neutral'], ['诗意', '清雅'], []],
  ['淇', 'qi', '水', '淇水、清美', ['female', 'neutral'], ['清雅', '诗意'], []],
  ['沛', 'pei', '水', '充沛、丰盈', ['male', 'neutral'], ['大气', '明朗'], []],
  ['霖', 'lin', '水', '甘霖、润泽', ['male', 'neutral'], ['温润', '大气'], ['overused']],
  ['雨', 'yu', '水', '雨露、滋养', ['female', 'male', 'neutral'], ['自然', '温润'], []],
  ['雪', 'xue', '水', '白雪、清洁', ['female', 'neutral'], ['清雅', '典雅'], []],
  ['云', 'yun', '水', '云气、舒卷', ['female', 'male', 'neutral'], ['诗意', '大气'], ['overused']],
  ['霁', 'ji', '水', '雨霁、晴朗', ['female', 'male', 'neutral'], ['清雅', '明朗'], []],
  ['润', 'run', '水', '润泽、温和', ['male', 'female', 'neutral'], ['温润', '文雅'], []],
  ['澈', 'che', '水', '清澈、透亮', ['male', 'female', 'neutral'], ['清雅', '简洁'], []],
  ['森', 'sen', '木', '森林、繁茂', ['male', 'neutral'], ['自然', '大气'], []],
  ['柏', 'bai', '木', '柏树、坚贞', ['male', 'neutral'], ['沉稳', '自然'], []],
  ['松', 'song', '木', '松柏、挺拔', ['male', 'neutral'], ['沉稳', '大气'], []],
  ['榆', 'yu', '木', '榆树、朴雅', ['male', 'female', 'neutral'], ['自然', '文雅'], []],
  ['槿', 'jin', '木', '木槿、温雅', ['female', 'neutral'], ['典雅', '自然'], []],
  ['禾', 'he', '木', '禾苗、生长', ['female', 'male', 'neutral'], ['自然', '简洁'], []],
  ['苏', 'su', '木', '复苏、舒展', ['female', 'male', 'neutral'], ['文雅', '清雅'], []],
  ['茗', 'ming', '木', '茶茗、清芬', ['female', 'male', 'neutral'], ['清雅', '书卷'], []],
  ['蕴', 'yun', '木', '蕴含、涵蓄', ['female', 'neutral'], ['文雅', '温润'], []],
  ['乔', 'qiao', '木', '乔木、高雅', ['male', 'female', 'neutral'], ['自然', '大气'], []],
  ['楚', 'chu', '木', '清楚、楚地', ['female', 'male', 'neutral'], ['诗意', '文雅'], ['overused']],
  ['榕', 'rong', '木', '榕树、葱茏', ['male', 'female', 'neutral'], ['自然', '大气'], []],
  ['菡', 'han', '木', '荷花、清芬', ['female'], ['清雅', '诗意'], []],
  ['茉', 'mo', '木', '茉莉、清香', ['female'], ['清雅', '自然'], []],
  ['芸', 'yun', '木', '芸香、书香', ['female', 'neutral'], ['书卷', '清雅'], []],
  ['晨', 'chen', '火', '清晨、初明', ['male', 'female', 'neutral'], ['明朗', '清雅'], ['overused']],
  ['晴', 'qing', '火', '晴朗、开明', ['female', 'neutral'], ['明朗', '清雅'], []],
  ['昭', 'zhao', '火', '昭明、清亮', ['male', 'female', 'neutral'], ['明朗', '典雅'], []],
  ['曜', 'yao', '火', '光曜、明亮', ['male', 'neutral'], ['大气', '明朗'], []],
  ['晟', 'sheng', '火', '光明、兴盛', ['male', 'neutral'], ['大气', '明朗'], ['overused']],
  ['熙', 'xi', '火', '和乐、光明', ['female', 'male', 'neutral'], ['温润', '明朗'], ['overused']],
  ['暖', 'nuan', '火', '温暖、和煦', ['female', 'neutral'], ['温润', '明朗'], []],
  ['晗', 'han', '火', '天将明', ['female', 'neutral'], ['清雅', '明朗'], ['overused']],
  ['暄', 'xuan', '火', '温暖、明朗', ['female', 'neutral'], ['温润', '清雅'], []],
  ['烨', 'ye', '火', '光华、明亮', ['male', 'neutral'], ['大气', '明朗'], []],
  ['炜', 'wei', '火', '光彩、鲜明', ['male', 'neutral'], ['大气', '明朗'], []],
  ['灿', 'can', '火', '灿然、明亮', ['female', 'male', 'neutral'], ['明朗', '大气'], []],
  ['朗', 'lang', '火', '晴朗、爽朗', ['male', 'neutral'], ['明朗', '简洁'], []],
  ['知', 'zhi', '火', '知礼、知明', ['female', 'male', 'neutral'], ['书卷', '文雅'], []],
  ['夏', 'xia', '火', '夏日、明朗', ['female', 'neutral'], ['明朗', '自然'], []],
  ['钧', 'jun', '金', '钧衡、分量', ['male', 'neutral'], ['沉稳', '大气'], []],
  ['铎', 'duo', '金', '木铎、教化', ['male', 'neutral'], ['大气', '书卷'], []],
  ['铄', 'shuo', '金', '明亮、熔炼', ['male', 'neutral'], ['明朗', '大气'], []],
  ['铠', 'kai', '金', '铠甲、坚毅', ['male'], ['沉稳', '大气'], []],
  ['钰', 'yu', '金', '珍宝、美玉', ['female', 'neutral'], ['典雅', '温润'], ['overused']],
  ['铭', 'ming', '金', '铭记、文辞', ['male', 'neutral'], ['沉稳', '书卷'], ['overused']],
  ['瑞', 'rui', '金', '祥瑞、美好', ['male', 'female', 'neutral'], ['大气', '典雅'], ['overused']],
  ['琛', 'chen', '金', '珍宝、宝玉', ['male', 'neutral'], ['典雅', '沉稳'], []],
  ['睿', 'rui', '金', '明智、通达', ['male', 'female', 'neutral'], ['书卷', '大气'], ['overused']],
  ['诗', 'shi', '金', '诗意、文采', ['female', 'neutral'], ['诗意', '书卷'], []],
  ['思', 'si', '金', '思考、怀想', ['female', 'male', 'neutral'], ['文雅', '书卷'], ['overused']],
  ['初', 'chu', '金', '初始、本真', ['female', 'male', 'neutral'], ['清雅', '简洁'], []],
  ['成', 'cheng', '金', '成就、完成', ['male', 'neutral'], ['沉稳', '简洁'], []],
  ['真', 'zhen', '金', '真诚、本真', ['female', 'male', 'neutral'], ['简洁', '温润'], []],
  ['然', 'ran', '金', '自然、安然', ['female', 'male', 'neutral'], ['温润', '自然'], ['overused']],
  ['宇', 'yu', '土', '屋宇、气度', ['male', 'neutral'], ['大气', '沉稳'], ['overused']],
  ['宥', 'you', '土', '宽宥、包容', ['male', 'female', 'neutral'], ['温润', '沉稳'], []],
  ['垚', 'yao', '土', '土高、厚重', ['male', 'neutral'], ['大气', '沉稳'], ['hard-to-read']],
  ['岚', 'lan', '土', '山岚、清气', ['female', 'neutral'], ['自然', '清雅'], []],
  ['衡', 'heng', '土', '平衡、持正', ['male', 'neutral'], ['沉稳', '大气'], []],
  ['远', 'yuan', '土', '远志、开阔', ['male', 'neutral'], ['大气', '文雅'], []],
  ['亦', 'yi', '土', '亦然、从容', ['female', 'male', 'neutral'], ['简洁', '文雅'], []],
  ['依', 'yi', '土', '依依、安定', ['female', 'neutral'], ['温润', '清雅'], ['overused']],
  ['允', 'yun', '土', '允正、诚信', ['female', 'male', 'neutral'], ['简洁', '文雅'], []],
  ['庭', 'ting', '土', '庭院、端正', ['male', 'female', 'neutral'], ['沉稳', '典雅'], []],
  ['佑', 'you', '土', '庇佑、辅助', ['male', 'neutral'], ['温润', '大气'], ['overused']],
  ['培', 'pei', '土', '培育、厚植', ['male', 'female', 'neutral'], ['沉稳', '温润'], []],
  ['坤', 'kun', '土', '厚载、广博', ['male', 'neutral'], ['沉稳', '大气'], []],
  ['岳', 'yue', '土', '山岳、稳重', ['male', 'neutral'], ['大气', '沉稳'], []],
  ['岩', 'yan', '土', '山岩、坚实', ['male', 'neutral'], ['沉稳', '自然'], []],
] satisfies HanziTuple[]).map(([char, pinyin, wuxing, meaning, genderFit, styleTags, riskTags = []], index) => ({
  id: `hanzi-sample-extra-${index + 1}`,
  char,
  pinyin,
  wuxing,
  meaning,
  genderFit,
  styleTags,
  riskTags,
  source: SAMPLE_HANZI_SOURCE,
}));

export const HANZI_SAMPLE: HanziKnowledgeCard[] = [
  { id: 'hanzi-qing', char: '清', pinyin: 'qing', wuxing: '水', meaning: '清澈、清正、清雅', genderFit: ['female', 'male', 'neutral'], styleTags: ['清雅', '温润'], riskTags: [], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-han', char: '涵', pinyin: 'han', wuxing: '水', meaning: '涵养、包容', genderFit: ['female', 'neutral'], styleTags: ['温润', '清雅'], riskTags: ['overused'], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-ze', char: '泽', pinyin: 'ze', wuxing: '水', meaning: '润泽、恩泽', genderFit: ['male', 'neutral'], styleTags: ['大气', '温润'], riskTags: ['overused'], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-yuan', char: '源', pinyin: 'yuan', wuxing: '水', meaning: '源流、本源', genderFit: ['male', 'neutral'], styleTags: ['大气', '文雅'], riskTags: [], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-mu', char: '沐', pinyin: 'mu', wuxing: '水', meaning: '润泽、沐养', genderFit: ['female', 'male', 'neutral'], styleTags: ['清雅', '自然'], riskTags: ['overused'], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-yang', char: '扬', pinyin: 'yang', wuxing: '火', meaning: '舒展、显扬、明朗', genderFit: ['female', 'male', 'neutral'], styleTags: ['清雅', '明朗'], riskTags: [], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-jin', char: '瑾', pinyin: 'jin', wuxing: '火', meaning: '美玉、德行', genderFit: ['female', 'neutral'], styleTags: ['典雅', '端庄'], riskTags: ['overused'], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-yu', char: '煜', pinyin: 'yu', wuxing: '火', meaning: '照耀、光明', genderFit: ['male', 'neutral'], styleTags: ['明朗', '大气'], riskTags: [], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-xi', char: '昕', pinyin: 'xin', wuxing: '火', meaning: '晨光、初明', genderFit: ['female', 'neutral'], styleTags: ['明朗', '清雅'], riskTags: [], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-nian', char: '念', pinyin: 'nian', wuxing: '火', meaning: '思念、记取', genderFit: ['female', 'neutral'], styleTags: ['文雅', '温润'], riskTags: [], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-lin', char: '琳', pinyin: 'lin', wuxing: '木', meaning: '美玉、琳琅', genderFit: ['female', 'neutral'], styleTags: ['典雅', '清雅'], riskTags: ['overused'], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-zhi', char: '芷', pinyin: 'zhi', wuxing: '木', meaning: '香草、清芬', genderFit: ['female'], styleTags: ['诗意', '清雅'], riskTags: [], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-tong', char: '桐', pinyin: 'tong', wuxing: '木', meaning: '梧桐、挺秀', genderFit: ['female', 'male', 'neutral'], styleTags: ['自然', '文雅'], riskTags: [], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-yan', char: '言', pinyin: 'yan', wuxing: '木', meaning: '言语、信言', genderFit: ['male', 'female', 'neutral'], styleTags: ['文雅', '简洁'], riskTags: [], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-ruo', char: '若', pinyin: 'ruo', wuxing: '木', meaning: '如若、柔美', genderFit: ['female', 'neutral'], styleTags: ['诗意', '清雅'], riskTags: [], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-jin-metal', char: '锦', pinyin: 'jin', wuxing: '金', meaning: '锦绣、华美', genderFit: ['female', 'male', 'neutral'], styleTags: ['典雅', '大气'], riskTags: ['overused'], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-shu', char: '书', pinyin: 'shu', wuxing: '金', meaning: '书卷、学识', genderFit: ['female', 'male', 'neutral'], styleTags: ['文雅', '书卷'], riskTags: [], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-yue', char: '悦', pinyin: 'yue', wuxing: '金', meaning: '喜悦、和乐', genderFit: ['female', 'neutral'], styleTags: ['明朗', '温润'], riskTags: [], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-an', char: '安', pinyin: 'an', wuxing: '土', meaning: '安定、安然', genderFit: ['female', 'male', 'neutral'], styleTags: ['温润', '简洁'], riskTags: ['overused'], source: SAMPLE_HANZI_SOURCE },
  { id: 'hanzi-chen', char: '辰', pinyin: 'chen', wuxing: '土', meaning: '星辰、时序', genderFit: ['male', 'female', 'neutral'], styleTags: ['大气', '明朗'], riskTags: ['overused'], source: SAMPLE_HANZI_SOURCE },
  ...ADDITIONAL_HANZI_SAMPLE,
];
